module.exports = {
    CONTEXT_LOCK_ACQUIRE: 'CONTEXT_LOCK_ACQUIRE',
    CONTEXT_LOCK_ACQUIRE_RESULT: 'CONTEXT_LOCK_ACQUIRE_RESULT',
    CONTEXT_LOCK_RELEASE: 'CONTEXT_LOCK_RELEASE',
    CONTEXT_LOCK_RELEASE_RESULT: 'CONTEXT_LOCK_RELEASE_RESULT',
    CONTEXT_LOCK_CHECK: 'CONTEXT_LOCK_CHECK',
    CONTEXT_LOCK_CHECK_RESULT: 'CONTEXT_LOCK_CHECK_RESULT',
    CACHE_GET: 'CACHE_GET',
    CACHE_GET_RESULT: 'CACHE_GET_RESULT',
    CACHE_SET: 'CACHE_SET',
    CACHE_SET_RESULT: 'CACHE_SET_RESULT'
};